import type { Metadata } from "next";
import { Outfit, Inter } from "next/font/google";
import { syncNotifications } from "@/lib/notifications";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  // Runs on every page load, internal or public, so notifications created by
  // public actions (e.g. accepting a quote, booking an appointment) still
  // get synced and their alert emails batched-and-flushed promptly — see
  // lib/notifications.ts. The header/bell UI that surfaces this data is
  // internal-only and lives in app/(internal)/layout.tsx instead.
  await syncNotifications();

  return (
    <html
      lang="en"
      className={`${outfit.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-canvas">{children}</body>
    </html>
  );
}
